import type { SchemaTypeDefinition } from './types';

export const schemaTypeDefinitions: SchemaTypeDefinition[] = [
	{
		type: 'Article',
		label: 'Bài viết',
		description: 'Bài viết thông thường, blog post',
		icon: 'article',
		fields: [
			{ name: 'headline', label: 'Tiêu đề', type: 'string', required: true },
			{ name: 'author', label: 'Tác giả', type: 'string' },
			{ name: 'authorUrl', label: 'URL tác giả', type: 'url' },
			{ name: 'datePublished', label: 'Ngày xuất bản', type: 'datetime' },
			{ name: 'dateModified', label: 'Ngày cập nhật', type: 'datetime' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'description', label: 'Mô tả', type: 'text' },
		],
	},
	{
		type: 'NewsArticle',
		label: 'Tin tức',
		description: 'Bài viết tin tức',
		icon: 'newspaper',
		fields: [
			{ name: 'headline', label: 'Tiêu đề', type: 'string', required: true },
			{ name: 'author', label: 'Tác giả', type: 'string' },
			{ name: 'datePublished', label: 'Ngày xuất bản', type: 'datetime', required: true },
			{ name: 'dateModified', label: 'Ngày cập nhật', type: 'datetime' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'description', label: 'Mô tả', type: 'text' },
		],
	},
	{
		type: 'BlogPosting',
		label: 'Blog Post',
		description: 'Bài đăng blog',
		icon: 'edit_note',
		fields: [
			{ name: 'headline', label: 'Tiêu đề', type: 'string', required: true },
			{ name: 'author', label: 'Tác giả', type: 'string' },
			{ name: 'authorUrl', label: 'URL tác giả', type: 'url' },
			{ name: 'datePublished', label: 'Ngày xuất bản', type: 'datetime' },
			{ name: 'dateModified', label: 'Ngày cập nhật', type: 'datetime' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'wordCount', label: 'Số từ', type: 'number' },
		],
	},
	{
		type: 'Product',
		label: 'Sản phẩm',
		description: 'Thông tin sản phẩm cho e-commerce',
		icon: 'shopping_bag',
		fields: [
			{ name: 'name', label: 'Tên sản phẩm', type: 'string', required: true },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'brand', label: 'Thương hiệu', type: 'string' },
			{ name: 'sku', label: 'SKU', type: 'string' },
			{ name: 'price', label: 'Giá', type: 'number' },
			{ name: 'priceCurrency', label: 'Loại tiền', type: 'string', placeholder: 'VND' },
			{ name: 'availability', label: 'Tình trạng', type: 'string', placeholder: 'InStock' },
			{ name: 'ratingValue', label: 'Đánh giá', type: 'number' },
			{ name: 'reviewCount', label: 'Số đánh giá', type: 'number' },
		],
	},
	{
		type: 'LocalBusiness',
		label: 'Doanh nghiệp địa phương',
		description: 'Thông tin doanh nghiệp, cửa hàng',
		icon: 'store',
		fields: [
			{ name: 'name', label: 'Tên doanh nghiệp', type: 'string', required: true },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'telephone', label: 'Điện thoại', type: 'string' },
			{ name: 'email', label: 'Email', type: 'string' },
			{ name: 'streetAddress', label: 'Địa chỉ', type: 'string' },
			{ name: 'addressLocality', label: 'Thành phố', type: 'string' },
			{ name: 'addressRegion', label: 'Tỉnh/Khu vực', type: 'string' },
			{ name: 'postalCode', label: 'Mã bưu điện', type: 'string' },
			{ name: 'addressCountry', label: 'Quốc gia', type: 'string', placeholder: 'VN' },
			{ name: 'latitude', label: 'Vĩ độ', type: 'number' },
			{ name: 'longitude', label: 'Kinh độ', type: 'number' },
			{ name: 'priceRange', label: 'Khoảng giá', type: 'string', placeholder: '$$' },
		],
	},
	{
		type: 'Organization',
		label: 'Tổ chức',
		description: 'Thông tin tổ chức, công ty',
		icon: 'business',
		fields: [
			{ name: 'name', label: 'Tên tổ chức', type: 'string', required: true },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'url', label: 'Website', type: 'url' },
			{ name: 'logo', label: 'Logo', type: 'image' },
			{ name: 'sameAs', label: 'Mạng xã hội (mỗi dòng 1 URL)', type: 'text', description: 'Facebook, LinkedIn, Twitter...' },
		],
	},
	{
		type: 'Person',
		label: 'Người',
		description: 'Thông tin cá nhân, tác giả',
		icon: 'person',
		fields: [
			{ name: 'name', label: 'Tên', type: 'string', required: true },
			{ name: 'image', label: 'Ảnh đại diện', type: 'image' },
			{ name: 'jobTitle', label: 'Chức danh', type: 'string' },
			{ name: 'url', label: 'Website', type: 'url' },
			{ name: 'sameAs', label: 'Mạng xã hội (mỗi dòng 1 URL)', type: 'text' },
		],
	},
	{
		type: 'FAQ',
		label: 'Câu hỏi thường gặp',
		description: 'Danh sách câu hỏi và trả lời',
		icon: 'quiz',
		fields: [
			{
				name: 'questions',
				label: 'Câu hỏi',
				type: 'array',
				items: {
					name: 'item',
					label: 'Câu hỏi',
					type: 'object',
					properties: [
						{ name: 'question', label: 'Câu hỏi', type: 'string', required: true },
						{ name: 'answer', label: 'Trả lời', type: 'text', required: true },
					],
				},
			},
		],
	},
	{
		type: 'HowTo',
		label: 'Hướng dẫn',
		description: 'Hướng dẫn từng bước',
		icon: 'checklist',
		fields: [
			{ name: 'name', label: 'Tiêu đề', type: 'string', required: true },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'totalTime', label: 'Tổng thời gian', type: 'string', placeholder: 'PT30M (30 phút)' },
			{ name: 'estimatedCost', label: 'Chi phí ước tính', type: 'string' },
			{
				name: 'steps',
				label: 'Các bước',
				type: 'array',
				items: {
					name: 'step',
					label: 'Bước',
					type: 'object',
					properties: [
						{ name: 'name', label: 'Tên bước', type: 'string', required: true },
						{ name: 'text', label: 'Nội dung', type: 'text', required: true },
						{ name: 'image', label: 'Hình ảnh', type: 'image' },
					],
				},
			},
		],
	},
	{
		type: 'Recipe',
		label: 'Công thức nấu ăn',
		description: 'Công thức món ăn',
		icon: 'restaurant',
		fields: [
			{ name: 'name', label: 'Tên món', type: 'string', required: true },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'author', label: 'Tác giả', type: 'string' },
			{ name: 'prepTime', label: 'Thời gian chuẩn bị', type: 'string', placeholder: 'PT15M' },
			{ name: 'cookTime', label: 'Thời gian nấu', type: 'string', placeholder: 'PT30M' },
			{ name: 'recipeYield', label: 'Khẩu phần', type: 'string', placeholder: '4 người' },
			{ name: 'recipeIngredient', label: 'Nguyên liệu (mỗi dòng 1 nguyên liệu)', type: 'text' },
			{ name: 'recipeInstructions', label: 'Cách làm (mỗi dòng 1 bước)', type: 'text' },
			{ name: 'calories', label: 'Calories', type: 'string' },
		],
	},
	{
		type: 'Event',
		label: 'Sự kiện',
		description: 'Thông tin sự kiện',
		icon: 'event',
		fields: [
			{ name: 'name', label: 'Tên sự kiện', type: 'string', required: true },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'image', label: 'Hình ảnh', type: 'image' },
			{ name: 'startDate', label: 'Ngày bắt đầu', type: 'datetime', required: true },
			{ name: 'endDate', label: 'Ngày kết thúc', type: 'datetime' },
			{ name: 'locationName', label: 'Tên địa điểm', type: 'string' },
			{ name: 'locationAddress', label: 'Địa chỉ', type: 'string' },
			{ name: 'performer', label: 'Người biểu diễn', type: 'string' },
			{ name: 'organizer', label: 'Nhà tổ chức', type: 'string' },
			{ name: 'eventStatus', label: 'Trạng thái', type: 'string', placeholder: 'EventScheduled' },
		],
	},
	{
		type: 'Course',
		label: 'Khóa học',
		description: 'Thông tin khóa học',
		icon: 'school',
		fields: [
			{ name: 'name', label: 'Tên khóa học', type: 'string', required: true },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'provider', label: 'Nhà cung cấp', type: 'string' },
			{ name: 'providerUrl', label: 'Website nhà cung cấp', type: 'url' },
		],
	},
	{
		type: 'BreadcrumbList',
		label: 'Breadcrumb',
		description: 'Đường dẫn điều hướng',
		icon: 'arrow_forward',
		fields: [
			{
				name: 'items',
				label: 'Các mục',
				type: 'array',
				items: {
					name: 'item',
					label: 'Mục',
					type: 'object',
					properties: [
						{ name: 'name', label: 'Tên', type: 'string', required: true },
						{ name: 'url', label: 'URL', type: 'url', required: true },
					],
				},
			},
		],
	},
	{
		type: 'WebPage',
		label: 'Trang web',
		description: 'Thông tin trang web chung',
		icon: 'web',
		fields: [
			{ name: 'name', label: 'Tên trang', type: 'string' },
			{ name: 'description', label: 'Mô tả', type: 'text' },
			{ name: 'url', label: 'URL', type: 'url' },
			{ name: 'datePublished', label: 'Ngày xuất bản', type: 'datetime' },
			{ name: 'dateModified', label: 'Ngày cập nhật', type: 'datetime' },
		],
	},
];

export function getSchemaDefinition(type: string): SchemaTypeDefinition | undefined {
	return schemaTypeDefinitions.find((def) => def.type === type);
}
